#开发环境配置数据源指向不同机器IP
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/quickshop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: admin123



jwt:
  secret: 7H+ViUYlLmcAxrA4e2arWlXZ2l2Vtv0CeC7MgUKZeIjFUFp3949qb5wRE/pX+w5cweTWxJFYKwkSGDHzACCXfw==
  validTime: 86400
